export * from './NowPlayingInterface'
export * from './PopularInterface'
export * from './TopRatedInterface'
export * from './UpComingInterface'
export * from './MovieInterface'
export * from './MovieDetailsInterface'